# docker build -t umn -f ./Dockerfile_node .

FROM	ubuntu14-mongodb3

MAINTAINER	Calvin Soh soh_calvin@yahoo.com

#install common dependencies needed by subsequent images
RUN apt-get update && apt-get install -y \
	    git \
	    gfortran \
	    libatlas-base-dev \
	    libblas-dev \ 
	    liblapack-dev \
	    nodejs \
	    nodejs-legacy \
	    npm \
	    python-bs4 \
	    python-dev \
	    python-nltk \
	    python3-pip \
	    ssh \
	    sudo \
	    supervisor  
